### ISSUE TITLE
Have commas (,) as defaults - not periods (.)

### ISSUE THREAD

**Issue by eivindkopperud** [Xtrah/ntnui-refusjon#29]
### Background
From feedback dated september 29:
> Er det mulig å endre defaulten for tall i refusjonskjemaene og reiseregningsskjemaene til å være komma(,) istendenfor punktum(.)
Hilsen en kasserer som elsker "copy-past" men er lei av å viske ut punktum og endre til komma for at danske bank skal bli fornøyd

### How is it today
See the image
![image](https://user-images.githubusercontent.com/43027083/200187213-f8b538b0-91df-4dc8-9935-89315cc767ca.png)

**Comment by matsfinsas** [comment]
Resolved in https://github.com/NTNUI/skjema/commit/4ec4b324ffef26b3be074bec0c4de8295393513b#diff-a23e4f6f8c884063609205fa3f8ce3165c06535d4ac4f56c07a8107cd4bb2d99R148 and https://github.com/NTNUI/skjema/commit/e6b7bec6e2aaeeaf15f862fcb794a2cc20b8dd2b#diff-a23e4f6f8c884063609205fa3f8ce3165c06535d4ac4f56c07a8107cd4bb2d99R162
