### ISSUE TITLE
of-watchdog is no longer on Docker Hub

### ISSUE THREAD

**Issue by matsfinsas** [Xtrah/ntnui-refusjon#34]
https://github.com/NTNUI/skjema/actions/runs/4430218613/jobs/7855046311

https://www.openfaas.com/blog/how-does-docker-hub-affect-openfaas/

## tl;dr

We need to pull from [GitHub Container Registry](https://github.com/openfaas/of-watchdog/pkgs/container/of-watchdog) to continue using it.

```bash
docker pull ghcr.io/openfaas/of-watchdog:0.9.11
```

**Comment by matsfinsas** [comment]
Resolved in f922359856d1068e441b72e3f416d8e838d6a31c

**Comment by eivindkopperud** [comment]
Nice!
